Repository milessabin/shapeless, pull requests merged in 2020-03, with the labels that each got.

#972 Tighten fieldsOf and isCaseAccessorLike
  core/src/main/scala/shapeless/annotation.scala
  core/src/main/scala/shapeless/generic.scala
  core/src/test/scala/shapeless/generic.scala
  core/src/test/scala/shapeless/labelledgeneric.scala
Labels: Bug, Design/refactoring

#973 Product length is Nat
  core/src/main/scala/shapeless/ops/products.scala
Labels: Bug

#705 Removed allocation in object Tag
  core/src/main/scala/shapeless/typeoperators.scala
Labels: Design/refactoring

#867 Support for Annotation[Option[A], T]
  core/src/main/scala/shapeless/annotation.scala
  core/src/test/scala/shapeless/annotation.scala
Labels: Feature

#708 Add bindFirst and curried methods for Poly
  core/src/main/scala/shapeless/poly.scala
  core/src/test/scala/shapeless/poly.scala
Labels: Feature

#982 Add note about erasure to HMap
  core/src/main/scala/shapeless/hmap.scala
Labels: Documentation

#988 Fix #771 - add regression test
  core/src/test/scala/shapeless/hlist.scala
Labels: Bug

#987 Fix #609 - add type annotation
  core/src/main/scala/shapeless/hlists.scala
Labels: Design/refactoring

#985 Cache coursier directory
  .travis.yml
Labels: Build

#983 Make illTyped blackbox
  core/src/main/scala/shapeless/test/typechecking.scala
Labels: Design/refactoring

#979 Constrain tuple syntax with IsTuple
  core/src/main/scala/shapeless/syntax/std/tuples.scala
  core/src/test/scala/shapeless/tuples.scala
Labels: Design/refactoring

#986 Fix #843 - add regression test
  :
  core/src/test/scala/shapeless/singletons.scala
Labels: Bug

#989 Fix #800 - add regression test
  core/src/test/scala/shapeless/singletons.scala
Labels: Bug

#803 Avoid creating Typeable for general type projections
  core/src/main/scala/shapeless/typeable.scala
  core/src/test/scala/shapeless/typeable.scala
Labels: Bug

#990 Fix #838 - add regression test
  core/src/test/scala/shapeless/typeclass.scala
Labels: Bug

#980 Poly builders require no import
  core/src/main/scala/shapeless/poly.scala
  core/src/test/scala/shapeless/poly.scala
  project/Boilerplate.scala
Labels: Design/refactoring

#991 Fix Lazy implicit resolution with type parameters
  core/src/main/scala/shapeless/lazy.scala
  core/src/test/scala/shapeless/lazy.scala
Labels: Bug

#981 making constraints more generic
  core/src/main/scala/shapeless/constraints.scala
  core/src/main/scala/shapeless/hlistconstraints.scala
  core/src/test/scala/shapeless/constraints.scala
  core/src/test/scala/shapeless/hlistconstraints.scala
Labels: Design/refactoring, Feature

#765 Fixed some scoping issues with Generic Coproducts
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/generic1.scala
  core/src/test/scala/shapeless/generic.scala
Labels: Bug, Design/refactoring

#992 Scala 2.12.11
  .travis.yml
  :
  build.sbt
Labels: Build

#993 Update sbt-sonatype to 3.9.1
  project/plugins.sbt
Labels: Build

#995 Update sbt-sonatype to 3.9.2
  project/plugins.sbt
Labels: Build

#994 Add mkAttributedRef specialized for SingleType
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/orphans.scala
Labels: Bug

#996 Setup sbt-ci-release
  .travis.yml
  build.sbt
  project/plugins.sbt
  scripts/travis-publish.sh
  version.sbt
Labels: Build

#999 Enable publishing of native module.
  .gitignore
  .jvmopts
  .travis.yml
  build.sbt
Labels: Build

#1001 Update sbt to 1.3.9
  project/build.properties
Labels: Build
