Repository milessabin/shapeless, pull requests merged in 2021-04, with the labels that each got.

#1107 Replace anonymous classes created by macros with instance helpers
  build.sbt
  core/jvm/src/test/scala/shapeless/serialization.scala
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/generic1.scala
  core/src/main/scala/shapeless/labelled.scala
  core/src/main/scala/shapeless/singletons.scala
  core/src/main/scala/shapeless/syntax/singletons.scala
Labels: Backport

#1113 sbt 1.5 and slash syntax (the old one is deprecated)
  build.sbt
  project/build.properties
Labels: Backport, Build

#1114 Improve implicit search times for Filter, FilterNot, Union, Intersection
  core/src/main/scala/shapeless/ops/hlists.scala
Labels: Backport, Performance

#1115 Removed allocation in object Tag
  core/src/main/scala/shapeless/typeoperators.scala
Labels: Backport, Performance

#1116 Fix Lazy for tagged types
  core/src/main/scala/shapeless/lazy.scala
  core/src/test/scala/shapeless/labelledgeneric.scala
  core/src/test/scala/shapeless/lazy.scala
Labels: Backport, Bug

#1118 Conversions between nested pairs and HLists
  core/src/main/scala/shapeless/ops/hlists.scala
  core/src/main/scala/shapeless/syntax/hlists.scala
  core/src/main/scala/shapeless/syntax/std/tuples.scala
  core/src/test/scala/shapeless/hlist.scala
  ~/.ivy2/.sbt.ivy.lock
Labels: Backport, Feature

#1119 Add bindFirst and curried methods for Poly
  core/src/main/scala/shapeless/poly.scala
  core/src/test/scala/shapeless/poly.scala
Labels: Backport, Feature

#1120 Loosen typeable restrictions
  core/src/main/scala/shapeless/typeable.scala
  core/src/test/scala/shapeless/typeable.scala
Labels: Backport, Bug

#1121 Fix Typeable.describe for symbolic names
  core/src/main/scala/shapeless/typeable.scala
  core/src/test/scala/shapeless/typeable.scala
Labels: Backport, Bug

#1122 Fix Typeable for inner classes
  core/src/main/scala/shapeless/typeable.scala
  core/src/test/scala/shapeless/typeable.scala
Labels: Backport, Bug

#1123 make Tagged a universal trait so tagging value classes works
  core/src/main/scala/shapeless/typeoperators.scala
  core/src/test/scala/shapeless/typeoperators.scala
Labels: Backport, Feature

#1124 Avoid creating Typeable for general type projections
  core/src/main/scala/shapeless/typeable.scala
  core/src/test/scala/shapeless/typeable.scala
Labels: Backport, Bug

#1125 Make Inject respect covariance
  core/src/main/scala/shapeless/ops/coproduct.scala
  core/src/test/scala/shapeless/coproduct.scala
Labels: Backport, Feature

#1126 Make Typeable macros not dependent on default Predef presence
  core/src/main/scala/shapeless/typeable.scala
Labels: Backport, Bug

#1127 Support for Annotation[Option[A], T]
  build.sbt
  core/src/main/scala/shapeless/annotation.scala
  core/src/test/scala/shapeless/annotation.scala
Labels: Backport, Feature

#1129 Optimize SelectRange typeclass derivation
  core/src/main/scala/shapeless/ops/hlists.scala
Labels: Backport, Performance

#1130 Tighten fieldsOf and isCaseAccessorLike
  build.sbt
  core/src/main/scala/shapeless/annotation.scala
  core/src/main/scala/shapeless/generic.scala
  core/src/test/scala/shapeless/generic.scala
  core/src/test/scala/shapeless/labelledgeneric.scala
Labels: Backport, Bug

#1131 Expose CaseClassMacros as blackbox
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/generic1.scala
Labels: Backport, Feature

#1132 Constrain tuple syntax with IsTuple
  core/src/main/scala/shapeless/syntax/std/tuples.scala
  core/src/test/scala/shapeless/tuples.scala
Labels: Backport, Bug

#1133 Add note about erasure to HMap
  core/src/main/scala/shapeless/hmap.scala
Labels: Backport, Documentation

#1135 Fix #609 - add type annotation
  core/src/main/scala/shapeless/hlists.scala
Labels: Backport, Design/refactoring

#1134 Add missing asInstanceOf call
  core/src/main/scala/shapeless/generic.scala
  core/src/test/scala_2.13+/shapeless/LabelledGenericTests213.scala
Labels: Backport, Bug

#1136 Fix Lazy implicit resolution with type parameters
  core/src/main/scala/shapeless/lazy.scala
  core/src/test/scala/shapeless/lazy.scala
Labels: Backport, Bug

#1137 Add mkAttributedRef specialized for SingleType
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/orphans.scala
Labels: Backport, Bug

#1138 Make KeyTag extend Any so we can tag value classes
  core/src/main/scala/shapeless/labelled.scala
  core/src/test/scala/shapeless/records.scala
Labels: Backport, Feature

#1128 Fixed some scoping issues with Generic Coproducts
  core/src/main/scala/shapeless/generic.scala
  core/src/main/scala/shapeless/generic1.scala
  core/src/test/scala/shapeless/generic.scala
Labels: Backport, Bug

#1139 Add docs
  core/src/main/scala/shapeless/alacarte.scala
  core/src/main/scala/shapeless/annotation.scala
  core/src/main/scala/shapeless/generic.scala
Labels: Backport, Documentation

#1140 Regression tests
  core/src/test/scala/shapeless/hlist.scala
  core/src/test/scala/shapeless/typeclass.scala
Labels: Backport, Testing

#1058 Add support to extract all variable or type annotations (issue #1051)
  core/src/main/scala/shapeless/annotation.scala
  core/src/test/scala/shapeless/annotation.scala
Labels: Feature

#1142 implementation of issue #922: Add support for type annotations
  core/src/main/scala/shapeless/annotation.scala
  core/src/test/scala/shapeless/annotation.scala
Labels: Backport, Feature

#1143 Add support to extract all variable or type annotations (issue #1051)
  core/src/main/scala/shapeless/annotation.scala
  core/src/test/scala/shapeless/annotation.scala
Labels: Backport, Feature

#1019 Compiler plugin
  .github/workflows/ci.yml
  build.sbt
  core/jvm/src/test/scala/shapeless/serialization.scala
  core/jvm/src/test/scala_2.13-/shapeless/lazy.scala
  core/src/main/scala/shapeless/cached.scala
  core/src/main/scala/shapeless/generic1.scala
  core/src/main/scala/shapeless/lazy.scala
  core/src/main/scala/shapeless/lowpriority.scala
  core/src/main/scala/shapeless/orelse.scala
  core/src/main/scala/shapeless/orphans.scala
  core/src/main/scala/shapeless/package.scala
  core/src/main/scala/shapeless/sybclass.scala
  core/src/main/scala/shapeless/typeclass.scala
  core/src/main/scala_2.13+/shapeless/versionspecifics.scala
  core/src/main/scala_2.13-/shapeless/LazyMacros.scala
  core/src/main/scala_2.13-/shapeless/versionspecifics.scala
  core/src/test/scala/shapeless/cached.scala
  core/src/test/scala/shapeless/generic1.scala
  core/src/test/scala/shapeless/implicits.scala
  core/src/test/scala/shapeless/lazy.scala
  core/src/test/scala/shapeless/lowpriority.scala
  core/src/test/scala/shapeless/lowpriorityderivation.scala
  core/src/test/scala/shapeless/orphans.scala
  core/src/test/scala/shapeless/sybclass.scala
  examples/src/main/scala/shapeless/examples/csv.scala
  examples/src/main/scala/shapeless/examples/deephlister.scala
  examples/src/main/scala/shapeless/examples/delta.scala
  examples/src/main/scala/shapeless/examples/derivation.scala
  examples/src/main/scala/shapeless/examples/flatten.scala
  examples/src/main/scala/shapeless/examples/functor.scala
  plugin/src/main/resources/scalac-plugin.xml
  plugin/src/main/scala_2.13+/shapeless/ShapelessPlugin.scala
  plugin/src/main/scala_2.13-/shapeless/ShapelessPlugin.scala
Labels: Feature

#675 Reorder ops.tuple.Replacer type params to match scaladoc and naming conventions
  core/src/main/scala/shapeless/ops/tuples.scala
  core/src/main/scala/shapeless/syntax/std/tuples.scala
Labels: Design/refactoring
